BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Sign In') BBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXX

        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX



XXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXX

XXX XXXXXXXXXXXXXXX gettext(u'Sign In') XXXXX

BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBB
XX XXXXXXXXXXXXXXX gettext(u'Please sign in with one\nof your existing third party accounts. Or, <a href="%(signup_url)s">sign up</a>\nfor a %(site_name)s account and sign in below:') SSSSSS SSSS SS SSSS SSS
SS SSSS SSSSSSSS SSSSS SSSSS SSSSSSSSS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS
SSS S SSSSSSSSSSSSS SSSSSSS SSS SSSS SS SSSSSSXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB
  XXXXX

  XXXX XXXXXXXXXXXXXXXXX gettext(u'or') XXXXXX

XXXXXX



BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB
XXX gettext(u'If you have not created an account yet, then please\n<a href="%(signup_url)s">sign up</a> first.') SS SSS SSSS SSS SSSSSSS SS SSSSSSS SSSS SSSS SSSSSS
SS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS SSSSSSXXXX
BBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX

  BBBBB
  XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot Password?') XXXXXXXXX
  XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX gettext(u'Sign In') XXXXXXXXXXXXXXXXXX

XXXXXXX
XXXXXX

XXXXXX

XXXXXX
XXXXXX

XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXX XX X
      XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXX X XXX X XXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXX X XXXXXXXXXX X XX
        XXXXX XXXXXXX X XXXXXXXX X XXXXXXXXXXX X XX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXX X XXXXXXXXX

        XXXXXXXXXXXXXXXXX X
          XXXXXXX XXXXXX
          XXXXXXX XXXXXXXXXXXXXX X XXXXX
        XXX
      XXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXX
BBBBBBBB

XXXXXXX