BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Sign Out') BBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXX

XXX XXXXXXXXXXXXXXXXXX gettext(u'Вы вошли, как') XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

XXX XXXXXXXXXXXXXXXXXXXX

XXX gettext(u'Are you sure you want to sign out?') XXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
  BBBBB
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX gettext(u'Sign Out') XXXXXXXXXXXXXX
XXXXXXX

XXXXXXX

BBBBBBBB
