BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Password Reset') BBBBBBBB

BBBBB BBBBBBB

XXXXX XXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXX gettext(u'Password Reset') XXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB

    XXX gettext(u"Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.") XXXX
XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Reset My Password') X XX
    XXXXXXX

BBBBBBBB

XXXXXX

XXXXXX

XXXXXX
XXXXXX

XXXXXXX